version: "3"

services:
  elasticsearch:
    build: ./deps/elasticsearch/
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - elasticsearch-log:/var/log
    ports:
      - "127.0.0.1:9202:9200"

volumes:
  elasticsearch-data: {}
  elasticsearch-log: {}
